# server {
#    listen 80;
#    server_name localhost;
#
#    location / {
#        proxy_pass http://app:3000;
#        proxy_set_header Host $host;
#        proxy_set_header X-Forwarded-Proto $scheme;
#    }
#}

server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    # /restore → restore.html
    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;

        # убрать .html из URL
        # если запросили /restore — отдать restore.html
        # если запросили /restore.html — редирект на /restore
    }
}